//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:51:05 ���� CST 
//


package com.videolive.model.webrepdata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hybird.red5sys.webrepdata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Totalinfo_QNAME = new QName("", "totalinfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hybird.red5sys.webrepdata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Webreps }
     * 
     */
    public Webreps createWebreps() {
        return new Webreps();
    }

    /**
     * Create an instance of {@link Cmdrep }
     * 
     */
    public Cmdrep createCmdrep() {
        return new Cmdrep();
    }

    /**
     * Create an instance of {@link Rooms }
     * 
     */
    public Rooms createRooms() {
        return new Rooms();
    }

    /**
     * Create an instance of {@link Weapon }
     * 
     */
    public Weapon createWeapon() {
        return new Weapon();
    }

    /**
     * Create an instance of {@link Webreps.Weapons }
     * 
     */
    public Webreps.Weapons createWebrepsWeapons() {
        return new Webreps.Weapons();
    }

    /**
     * Create an instance of {@link Msg }
     * 
     */
    public Msg createMsg() {
        return new Msg();
    }

    /**
     * Create an instance of {@link Rooms.Roominfo }
     * 
     */
    public Rooms.Roominfo createRoomsRoominfo() {
        return new Rooms.Roominfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "totalinfo")
    public JAXBElement<Object> createTotalinfo(Object value) {
        return new JAXBElement<Object>(_Totalinfo_QNAME, Object.class, null, value);
    }

}
