//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:51:05 ���� CST 
//


package com.videolive.model.webrepdata;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="roominfo" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="people" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="imageurl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ishot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "roominfo"
})
@XmlRootElement(name = "rooms")
public class Rooms {

    protected List<Rooms.Roominfo> roominfo;

    /**
     * Gets the value of the roominfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roominfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoominfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rooms.Roominfo }
     * 
     * 
     */
    public List<Rooms.Roominfo> getRoominfo() {
        if (roominfo == null) {
            roominfo = new ArrayList<Rooms.Roominfo>();
        }
        return this.roominfo;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="people" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="imageurl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ishot" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name",
        "type",
        "people",
        "imageurl",
        "ishot"
    })
    public static class Roominfo {

        @XmlElement(required = true)
        protected String id;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String people;
        @XmlElement(required = true)
        protected String imageurl;
        @XmlElement(required = true)
        protected String ishot;
        

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the people property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPeople() {
            return people;
        }

        /**
         * Sets the value of the people property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPeople(String value) {
            this.people = value;
        }

        /**
         * Gets the value of the imageurl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImageurl() {
            return imageurl;
        }

        /**
         * Sets the value of the imageurl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImageurl(String value) {
            this.imageurl = value;
        }

        /**
         * Gets the value of the ishot property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIshot() {
            return ishot;
        }

        /**
         * Sets the value of the ishot property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIshot(String value) {
            this.ishot = value;
        }

    }

}
