//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:51:05 ���� CST 
//


package com.videolive.model.webrepdata;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}rooms" minOccurs="0"/>
 *         &lt;element ref="{}msg" minOccurs="0"/>
 *         &lt;element ref="{}cmdrep" minOccurs="0"/>
 *         &lt;element ref="{}totalinfo"/>
 *         &lt;element name="weapons">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}weapon" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="errorcode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rooms",
    "msg",
    "cmdrep",
    "totalinfo",
    "weapons"
})
@XmlRootElement(name = "webreps")
public class Webreps {

    protected Rooms rooms;
    protected Msg msg;
    protected Cmdrep cmdrep;
    @XmlElement(required = true)
    protected Object totalinfo;
    @XmlElement(required = true)
    protected Webreps.Weapons weapons;
    @XmlAttribute
    protected String desc;
    @XmlAttribute
    protected String errorcode;

    /**
     * Gets the value of the rooms property.
     * 
     * @return
     *     possible object is
     *     {@link Rooms }
     *     
     */
    public Rooms getRooms() {
        return rooms;
    }

    /**
     * Sets the value of the rooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rooms }
     *     
     */
    public void setRooms(Rooms value) {
        this.rooms = value;
    }

    /**
     * Gets the value of the msg property.
     * 
     * @return
     *     possible object is
     *     {@link Msg }
     *     
     */
    public Msg getMsg() {
        return msg;
    }

    /**
     * Sets the value of the msg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Msg }
     *     
     */
    public void setMsg(Msg value) {
        this.msg = value;
    }

    /**
     * Gets the value of the cmdrep property.
     * 
     * @return
     *     possible object is
     *     {@link Cmdrep }
     *     
     */
    public Cmdrep getCmdrep() {
        return cmdrep;
    }

    /**
     * Sets the value of the cmdrep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cmdrep }
     *     
     */
    public void setCmdrep(Cmdrep value) {
        this.cmdrep = value;
    }

    /**
     * Gets the value of the totalinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTotalinfo() {
        return totalinfo;
    }

    /**
     * Sets the value of the totalinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTotalinfo(Object value) {
        this.totalinfo = value;
    }

    /**
     * Gets the value of the weapons property.
     * 
     * @return
     *     possible object is
     *     {@link Webreps.Weapons }
     *     
     */
    public Webreps.Weapons getWeapons() {
        return weapons;
    }

    /**
     * Sets the value of the weapons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Webreps.Weapons }
     *     
     */
    public void setWeapons(Webreps.Weapons value) {
        this.weapons = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the errorcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorcode() {
        return errorcode;
    }

    /**
     * Sets the value of the errorcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorcode(String value) {
        this.errorcode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}weapon" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "weapon"
    })
    public static class Weapons {

        @XmlElement(required = true)
        protected List<Weapon> weapon;

        /**
         * Gets the value of the weapon property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the weapon property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getWeapon().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Weapon }
         * 
         * 
         */
        public List<Weapon> getWeapon() {
            if (weapon == null) {
                weapon = new ArrayList<Weapon>();
            }
            return this.weapon;
        }

    }

}
